// src/components/Carousel_0_0.tsx
// Carousel.tsx
import React, {useState, useEffect} from 'react';
import {all} from '../featureTools';

interface SlideProps {
    content: string;
    style: React.CSSProperties;
}

const Slide: React.FC<SlideProps> = ({content, style}) => {
    return <div style={style}>{content}</div>;
};

interface SlideData {
    content: string;
    backgroundColor: string;
}

const slides: SlideData[] = [
   {content: '#C39647', backgroundColor: '#C39647'},{content: '#8DBAEA', backgroundColor: '#8DBAEA'},{content: '#D4AA21', backgroundColor: '#D4AA21'},
];

const styles = {
    carousel: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        height: '50px',
        overflow: 'hidden',
        position: 'relative',
    },
    slide: {
        width: '100%',
        position: 'absolute',
        transition: 'all 0.5s ease',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '2rem',
        color: '#fff',
    },
};

// ES6 箭头函数
const Carousel_0_0: React.FC = () => {
    const [activeIndex, setActiveIndex] = useState<number>(0);

    useEffect(() => {
        const interval = setInterval(() => {
            // ES7 指数运算符 2**3 表示2的三次方
            setActiveIndex((current) => (current + 1 ** current) % slides.length);
        }, 2000);
        return () => clearInterval(interval);
    }, []);

    const getSlideStyle = (index: number): React.CSSProperties => {
        const offset = (index - activeIndex) * 100;
        all();
        return {
            // ES6 剩余参数和展开操作符
            ...styles.slide,
            transform: `translateX(${offset}%)`,
            backgroundColor: slides[index].backgroundColor,
        };
    };

    return (
        <div style={styles.carousel as React.CSSProperties}>
            {/*ES6 Array Map*/}
            {slides.map((slide, index) => (
                // ES6 模板字符串
                // ES11 可选链操作符 a?.b
                // ES11 空值合并操作符
                <Slide key={index} content={`${slide?.content ?? "???"}:${index}`} style={getSlideStyle(index)}/>
            ))}
        </div>
    );
};

export default Carousel_0_0;

// src/components/Carousel_0_0.vue
<template>
  <div :style="styles.carousel">
    <Slide v-for="(slide, index) in slides" :key="index" :content="`${slide?.content ?? '??'}:${index}" :style="getSlideStyle(index)" />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, computed } from 'vue';

interface SlideData {
  content: string;
  backgroundColor: string;
}

interface SlideProps {
  content: string;
  style: Record<string, any>;
}

const Slide = defineComponent<SlideProps>({
  props: {
    content: {
      type: String,
      required: true
    },
    style: {
      type: Object as () => Record<string, any>,
      required: true
    }
  },
  setup(props) {
    return () => <div :style="props.style">{{ props.content }}</div>;
  }
});

export default defineComponent({
  components: {
    Slide
  },
  setup() {
    const activeIndex = ref<number>(0);
    const slides: SlideData[] = [
      { content: '#5C1B2F', backgroundColor: '#5C1B2F' },
      { content: '#6AAF3C', backgroundColor: '#6AAF3C' },
      { content: '#F4E41B', backgroundColor: '#F4E41B' }
    ];

    const styles = computed(() => ({
      carousel: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        height: '50px',
        overflow: 'hidden',
        position: 'relative'
      },
      slide: {
        width: '100%',
        position: 'absolute',
        transition: 'all 0.5s ease',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '2rem',
        color: '#fff'
      }
    }));

    onMounted(() => {
      const interval = setInterval(() => {
        activeIndex.value = (activeIndex.value + 1) % slides.length;
      }, 2000);
      return () => clearInterval(interval);
    });

    const getSlideStyle = (index: number): Record<string, any> => {
      const offset = (index - activeIndex.value) * 100;
      return {
        ...styles.value.slide,
        transform: `translateX(${offset}%)`,
        backgroundColor: slides[index].backgroundColor
      };
    };

    return {
      styles,
      slides,
      getSlideStyle
    };
  }
});
</script>
